#!/bin/bash
#SBATCH -J LDpred2pc
#SBATCH -A CWALLACE-SL2-CPU # Long run, we're using SL2 instead
#SBATCH --nodes 1
#SBATCH --ntasks 15
#SBATCH --time 09:00:00
#SBATCH --mail-type FAIL
#SBATCH -p skylake-himem
#SBATCH --output=./err/%A_%a.err
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load r-4.0.2-gcc-5.4.0-xyx46xb
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
G=$SLURM_ARRAY_TASK_ID ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file
Rscript /home/gr440/rds/rds-cew54-basis/05-PGS/v3/code/LDpred2_perchr_run_20210317.R  $G
