#!/bin/bash
#SBATCH -J SBayesR
#SBATCH -A CWALLACE-SL2-CPU # USIGN SL2 here
#SBATCH --nodes 1
#SBATCH --ntasks 15
#SBATCH --time 08:00:00
#SBATCH --mail-type FAIL
#SBATCH -p skylake-himem
#SBATCH --output=./err/%A_%a.err
. /etc/profile.d/modules.sh # Leave this line (enables the module command)
module purge                # Removes all modules still loaded
#module load default-impi    # REQUIRED - loads the basic environment
module load rhel7/default-peta4            # REQUIRED - loads the basic environment
module load r-4.0.2-gcc-5.4.0-xyx46xb
export I_MPI_PIN_ORDER=scatter # Adjacent domains have minimal sharing of caches/sockets
JOBID=$SLURM_JOB_ID
echo -e "JobID: $JOBID"
G=$SLURM_ARRAY_TASK_ID ### this is the array variable, you can use it the way you want. In this example I use it to select the gene based on the line number in a file

trait=(Asthma RA T1D T2D BRCA PRCA CAD MDD BMI Height RAint)
N=$((G - 1))
T=${trait[@]:$N:1}

# Following recommendations from the GCTB FAQ page to avoid convergence problems, we 
# (1) In files with per-SNP N, we removed those in the lower 10% quantile (see preprocessing script).
# (2) Since for most datasets average sample sizes are given, we used the parameter --impute-n, to let GCTB to impute the per-snp size, as recommended. 
# (3) We added two parameters, to filter by p-value and LD: --p-value 0.5, and --rsq 0.99. See https://www.dropbox.com/sh/9aougeoxw4ygo8k/AAD6PT3a3ggv1-KYHytbeUNha?dl=0&preview=SBayesR_locke_wood_convergence.docx for details.
./gctb_2.02_Linux/gctb --sbayes R --mldm ../references/SBayesR/ukbEURu_hm3_sparse_mldm_list.txt --pi 0.95,0.02,0.02,0.01 --gamma 0.0,0.01,0.1,1 --gwas-summary ../datasets/"$T"_SBayesR.ma --chain-length 10000  --burn-in 2000 --out-freq 10 --impute-n --p-value 0.5 --rsq 0.99 --out ../models/"$T"_SBayesR
sed -e '1s/Chrom/CHR/' -e '1s/Position/BP/' -e '1s/A1Effect/weight/' -e '1s/A2/REF/' -e '1s/A1/ALT/' ../models/"$T"_SBayesR.snpRes > ../models/"$T"_hm3_SBayesR.full.model
mv ../models/"$T"_SBayesR.* ../models/SBayesR_extra


